yae/urls.py
from django.urls import path
from . import views

app_name = 'yae'

urlpatterns = [
    path('', views.home, name='home'),
    path('docs/',views.docs, name='docs'),
    path('dash/',views.dash, name='dash'),
    path('signup/',views.signup, name='register'),
]

yae_frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yae.urls')),
]

yae/models.py
from django.db import models

# Create your models here.

yae/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'yae/home.html', { 'title': "Home" })

def docs(request):
    return render(request, 'yae/docs.html', { 'title': 'Documentation' })

def dash(request):
    return render(request, 'yae/dash.html', { 'title': 'Dashboard'})

def signup(request):
    return render(request, 'yae/signup.html', { 'title': 'Register'})

yae/templates/yae/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'yae/images/favicon.ico' %}" type="icon/x-image">
    <link rel="stylesheet" href="{% static 'yae/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alexandria&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% if title %}
        <title>{{ title }} - Yae Miko | Discord Bot </title>
    {% else %}
        <title>Yae Miko | Discord Bot</title>
    {% endif %}
</head>
<body>
    <div class="navigation fixed-top container-fluid px-2">
        <nav class="navbar navbar-expand-md py-0">
            <a href="#" class="navbar-brand">
                <img src="{% static 'yae/images/brand.png' %}" alt="" height="48" width="auto">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#toggleNav" aria-controls="toggleNav" aria-expanded="false" aria-label="Toggle Navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="toggleNav">
                <ul class="navbar-nav text-center">
                    <li class="nav-item" >
                        <a id="home" class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'yae:home' %}">HOME</a>
                    </li>
                    <li class="nav-item" >
                        <a id="docs" class="nav-link {% if request.resolver_match.url_name == 'docs' %}active{% endif %}" href="{% url 'yae:docs' %}">DOCS</a>
                    </li class="nav-item" >
                    <li>
                        <a id="github" class="nav-link" href="https://github.com/cxrvxxxx/yae-miko">GITHUB</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}{% endblock content %}
    <footer>
        <small>Website created by: Brent Uriel M. Empasis | Background Image by @nolc_00 &copy;</small>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

yae/templates/yae/dash.html
{% extends "yae/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row min-vh-100 align-items-center justify-content-center">
        <h4 class="heading text-center infocard col-sm-6 py-5">This page is still under construction.</h4>
    </div>
</div>
{% endblock content %}

yae/templates/yae/docs.html
{% extends "yae/base.html" %}
{% load static %}
{% block content %}
<div class="docs-content container mt-5 py-5">
    <div class="row mt-1">
        <div class="docs-navi col-md-3 text-center py-3">
            <h5 class="docs-section">Getting started</h5>
        </div>
        <div class="docs-entry col-md-9 p-3">
            <h6 class="docs-subsection">Yae Miko &mdash; Discord Bot</h6>
            <span class="docs-subtext">Yae Miko is a Discord Bot built using Python & Discord.py library. It includes a multitude of features allowing you to manage your server using commands from the chat box as well as security functionality that protects your server from unwanted spams, trolls, and many other security risks making your server a safer place for its members.</span>
            <hr>
            <h6 class="docs-subsection">Adding Yae Miko to your Discord server</h6>
            <span class="docs-subtext">To start using Yae Miko, you can add the bot to your server by using the invite link below <br>
                <input class="codeblock" type="text" value="https://discord.com/api/oauth2/authorize?client_id=904245816552742922&permissions=1789390220887&scope=bot%20applications.commands" readonly>
                Copy the link above and paste it to your browser
            </span><br><br>
        </div>
    </div>
    <div class="row mt-1">
        <div class="docs-navi col-md-3 text-center py-3">
            <h5 class="docs-section">Usage instructions</h5>
        </div>
        <div class="docs-entry col-md-9 p-3">
            <h6 class="docs-subsection">Using Yae Miko</h6>
            <span class="docs-subtext">Yae Miko can receive commands from any text channels it has access to. To send a command, the default prefix is "y!" but it can be changed to any prefix of your preference later using a command. The format for text-based commands are as follows</span>
            <input class="codeblock" type="text" value="<prefix><command> <args>" readonly>
            <br>
            <span>Example:</span>
            <input class="codeblock" type="text" value="y!echo Hello!" readonly><br>
            <span class="docs-subtext">Where "y!" is the prefix, "echo" is the command, and "Hello!" is the argument.</span> <br><br>
        </div>
    </div>
    <div class="row mt-1">
        <div class="docs-navi col-md-3 text-center py-3">
            <h5 class="docs-section">Modules</h5>
        </div>
        <div class="docs-entry col-md-9 p-3">
            <h6 class="docs-subsection">Admin Module</h6>
            <span class="docs-subtext">This module contains commands that allows you to manage the operation of the bot. These commands require elevated permissions by default.</span> <br> <br>
            <table class="table w-100">
                <tr>
                    <th class="col-md-3">Command</th>
                    <th class="col-md-9">Description</th>
                </tr>
                <tr>
                    <td>setprefix prefix</td>
                    <td>Set the prefix for the current server to the one specified.</td>
                </tr>
                <tr>
                    <td>yaechannel</td>
                    <td>Set the current channel in the current server to be used only for Yae Miko commands. Invalid commands and regular chat will automatically be deleted.</td>
                </tr>
                <tr>
                    <td>setaccess @user 0-5</td>
                    <td>Set the mentioned user's access level to the one specified. This allows access to certain commands that require elevated permissions.</td>
                </tr>
                <tr>
                    <td>sudo</td>
                    <td>Gives the user the highest access level available.</td>
                </tr>
                <tr>
                    <td>restart</td>
                    <td>Restars the bot. Restricted to the bot owner only.</td>
                </tr>
                <tr>
                    <td>sync optional: -c/-g</td>
                    <td>Sync application commands. Use with "-c" to clear, "-g" to sync globally, or none to sync locally.</td>
                </tr>
                <tr>
                    <td>echo message</td>
                    <td>Makes the bot repeat the message.</td>
                </tr>
            </table>
            <hr>
            <h6 class="docs-subsection">Info Module</h6>
            <span class="docs-subtext">This module contains commands that displays information about other modules such as subcommands and usage specifications.</span> <br> <br>
            <table class="table w-100">
                <tr>
                    <th class="col-md-3">Command</th>
                    <th class="col-md-9">Description</th>
                </tr>
                <tr>
                    <td>info</td>
                    <td>Shows information about Yae Miko.</td>
                </tr>
                <tr>
                    <td>admin</td>
                    <td>Shows information about the Admin Module.</td>
                </tr>
                <tr>
                    <td>spam</td>
                    <td>Shows information about the Anti-spam Module.</td>
                </tr>
                <tr>
                    <td>music</td>
                    <td>Shows information about the MusicPlayer Module.</td>
                </tr>
                <tr>
                    <td>extras</td>
                    <td>Shows information about the Extras Module.</td>
                </tr>
                <tr>
                    <td>slash</td>
                    <td>Shows information about the Slash Commands Module.</td>
                </tr>
            </table>
            <hr>
            <h6 class="docs-subsection">Anti-spam Module</h6>
            <span class="docs-subtext">This module prevents spam. Currently there are no commands present in this module and operates by listening to message events in the server.</span>
            <hr>
            <h6 class="docs-subsection">MusicPlayer Mdodule</h6>
            <span class="docs-subtext">This module contains commands related to playing music in voice channels in the server. (Will be deprecated soon, replaced by slash commands.</span> <br><br>
            <table class="table w-100">
                <tr>
                    <th class="col-md-3">Command</th>
                    <th class="col-md-9">Description</th>
                </tr>
                <tr>
                    <td>join</td>
                    <td>Makes the bot join the user's current voice channel.</td>
                </tr>
                <tr>
                    <td>leave</td>
                    <td>Makes the bot leave the voice channel.</td>
                </tr>
                <tr>
                    <td>play title/url</td>
                    <td>Play the specified song/url in the voice channel.</td>
                </tr>
                <tr>
                    <td>stop</td>
                    <td>Stop playback in the current channel and clears the queue.</td>
                </tr>
                <tr>
                    <td>pause</td>
                    <td>Pause playback in the current channel.</td>
                </tr>
                <tr>
                    <td>resume</td>
                    <td>Resume playback in the current channel.</td>
                </tr>
                <tr>
                    <td>skip</td>
                    <td>Play the next song in the queue.</td>
                </tr>
                <tr>
                    <td>prev</td>
                    <td>Play the previously played song.</td>
                </tr>
                <tr>
                    <td>vol</td>
                    <td>Set the player's volume.</td>
                </tr>
                <tr>
                    <td>fave optional:title</td>
                    <td>Add the currently playing song to your list of favorites. If a title is specified, add that instead.</td>
                </tr>
                <tr>
                    <td>unfave index</td>
                    <td>Removes the song specified with the idnex argument from your list of favorites.</td>
                </tr>
                <tr>
                    <td>playliked optional:index</td>
                    <td>Add your list of favorite songs to the queue. If an index is specified, only add that instead.</td>
                </tr>
            </table>
            <hr>
            <h6 class="docs-subsection">Slash Commands Module</h6>
            <span class="docs-subtext">This module contains a list of application commands. These commands do not use the standard prefix syntax and instead use "/" as a prefix.</span><br><br>
            <table class="table w-100">
                <tr>
                    <th class="col-md-3">Command</th>
                    <th class="col-md-9">Description</th>
                </tr>
                <tr>
                    <td>whois @user</td>
                    <td>Shows information about the mentioned user.</td>
                </tr>
            </table>
            <hr>
            <h6 class="docs-subsection">Extras Module</h6>
            <span class="docs-subtext">This module contains commands that do not classify in any of the categories above.</span><br><br>
            <table class="table w-100">
                <tr>
                    <th class="col-md-3">Command</th>
                    <th class="col-md-9">Description</th>
                </tr>
                <tr>
                    <td>coinflip</td>
                    <td>Flip a coin</td>
                </tr>
            </table><br><br>
        </div>
    </div>
</div>
{% endblock content %}

yae/templates/yae/home.html
{% extends "yae/base.html" %}
{% load static %}
{% block content %}
<div class="content container mt-5 p-5">
    <div class="row text-center">
        <h1 class="heading" >Yae Miko &mdash; A bot for all your Discord server's needs!</h1>
    </div>
    <div class="row d-flex align-items-center">
      <div class="col-md-4">
        <div class="infocard card row mt-5">
          <h4>Login</h4>
          <form action="{% url 'yae:dash' %}" method="get">
            <div class="form-group">
              <!-- <label for="emailField">Email address</label> -->
              <input type="email" class="form-control" id="emailField" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <!-- <label for="exampleInputPassword1">Password</label> -->
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Remember password?</label>
            </div>
            <div class="btn-container row pt-4 gy-1 justify-content-between">
              <button form="register" type="submit" class="button button-secondary col-sm-12 col-md-6 col-lg-5">Register</button>
              <button type="submit" class="button col-sm-12 col-md-6 col-lg-5">Login</button>
            </div>
          </form>
          <form id="register" action="{% url 'yae:register' %}" method="get">
          </form>
        </div>
        <div class="invite infocard card row mt-5">   
          <h6 class="text-center" >Add Yae Miko to your server using this link</h6>
          <input id="inviteLinkField" class="invite-link mt-2" type="text" value="https://discord.com/api/oauth2/authorize?client_id=904245816552742922&permissions=1789390220887&scope=bot%20applications.commands" readonly>
          <input id="copyLinkBtn" type="button" class="button mt-2" onclick="copyLink()" value="COPY INVITE LINK" >
        </div>
      </div>
      <div class="col-md-7">
          <div class="row justify-content-evenly d-none">
              <div class="col-sm-6 infocard card mt-5" style="width: 18rem;">
                  <img class="infocard-img card-img-top" src="{% static 'yae/images/icon2.png' %}" alt="YaeMiko logo" height="240">
                  <div class="card-body">
                    <p class="card-text">Comes feature-packed and is capable of a multitude of tasks such as server management, moderation, react-roles, economy, music & entertainment, security features, and so much more! <br><br> Now supports slash commands!</p>
                  </div>
              </div>
              <div class="col-sm-6 infocard card mt-5" style="width: 18rem;">
                  <img class="infocard-img card-img-top" src="https://imgs.search.brave.com/GGfNfe5rxJ8QWEoxXniSLc0-POLU3qPyTIpuqPdbmXk/rs:fit:200:200:1/g:ce/aHR0cHM6Ly93d3cu/cHl0aG9uLm9yZy9z/dGF0aWMvb3Blbmdy/YXBoLWljb24tMjAw/eDIwMC5wbmc" alt="Python logo" height="240">
                  <div class="card-body">
                    <p class="card-text">Built using Python & discord.py <br><br>Asynchronus &mdash; Fast and responsive.<br>Well maintained &mdash; Bug fixes and constant updates.</p>
                  </div>
              </div>
          </div>
      </div>
    </div>
</div>
<script src="{% static 'yae/js/home.js' %}"></script>
{% endblock content %}

yae/templates/yae/signup.html
{% extends "yae/base.html" %}
{% load static %}
{% block content %}
<div class="container py-5 my-5 w-md-50">
    <div class="row signup">
        <h4>Registration</h4>
        <form action="{% url 'yae:home' %}" method="get">
          <div class="row">
            <div class="form-group col-md-12">
              <label for="emailField">Email address</label>
              <input type="email" class="form-control" id="emailField" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group col-md-6">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group col-md-6">
                <label for="exampleInputPassword1">Confirm Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
            <div class="checkboxes py-3">
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">I have agreed to the Terms & Conditions</label>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Sign up for newsletter</label>
              </div>
            </div>
            <button type="submit" class="button">Submit</button>
          </div>
          </form>
    </div>
</div>
{% endblock content %}